# Generated by Django 3.0.3 on 2020-02-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywebapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='completed',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
